monitor.alsa.rules = [
  # Rename sinks
  {
    matches = [
      {
        node.name = "alsa_output.usb-KTMicro_KT_USB_AUDIO_214b206000000178-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Desktop Headphones"
        node.nick = "Headphones"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_c1_00.1.HiFi__HDMI3__sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "Monitor (HDMI)"
        node.nick = "Monitor"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_card.pci-0000_c1_00.6"
      }
      {
        node.name = "alsa_output.pci-0000_c1_00.6.HiFi__Speaker__sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "Laptop Speakers"
        node.nick = "Laptop"
      }
    }
  }
  {
    matches = [
      {
        node.name = "bluez_output.84_9D_4B_78_92_C1.1"
      }
    ]
    actions = {
      update-props = {
        node.description = "Soundcore Headphones"
        node.nick = "Headphones"
      }
    }
  }

  # Rename sources
  {
    matches = [
      {
        node.name = "alsa_input.usb-046d_C922_Pro_Stream_Webcam_80CF11EF-02.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Logitech Webcam Mic"
        node.nick = "Webcam Mic"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.pci-0000_c1_00.6.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Laptop Mic"
        node.nick = "Laptop Mic"
      }
    }
  }

  # Disable unused devices
  {
    matches = [
      # Disable the audio sinks for the other three HDMI / USB-C ports.
      # Re-add these if I ever plug a monitor into a different laptop port.
      {
        node.name = "alsa_output.pci-0000_c1_00.1.HiFi__HDMI1__sink"
      }
      {
        node.name = "alsa_output.pci-0000_c1_00.1.HiFi__HDMI2__sink"
      }
      {
        node.name = "alsa_output.pci-0000_c1_00.1.HiFi__HDMI4__sink"
      }

      # Disable audio output on the Blue Yeti mic which I don't use
      {
        node.name = "alsa_output.usb-Blue_Microphones_Yeti_X_1943SG005M68_888-000313110306-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
