monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-KTMicro_KT_USB_AUDIO_214b206000000178-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Desktop Headphones"
        node.nick = "Headphones"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_c1_00.1.hdmi-stereo-extra2"
      }
    ]
    actions = {
      update-props = {
        node.description = "Monitor (HDMI)"
        node.nick = "Monitor"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_c1_00.6.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Laptop Speakers"
        node.nick = "Laptop"
      }
    }
  }

  # Disable the audio sinks for the other three HDMI / USB-C ports.
  # Re-add these if I ever plug a monitor into a different laptop port.
  {
    matches = [
      {
        node.name = "alsa_output.usb-Blue_Microphones_Yeti_X_1943SG005M68_888-000313110306-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }

  {
    matches = [
      {
        node.name = "alsa_input.usb-046d_C922_Pro_Stream_Webcam_80CF11EF-02.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Logitech Webcam Mic"
        node.nick = "Webcam Mic"
      }
    }
  }

  {
    matches = [
      {
        node.name = "alsa_input.pci-0000_c1_00.6.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Laptop Mic"
        node.nick = "Laptop Mic"
      }
    }
  }
]
