#!/bin/sh

HOST=`hostname | cut -d. -f1`

if [ -f "$HOME/.secure/$HOST/mutt/credentials" ]; then
  if [ ! -h "$HOME/.mutt/credentials" ] || [ `readlink $HOME/.mutt/credentials` != "$HOME/.secure/$HOST/mutt/credentials" ]; then
    ln -s $HOME/.secure/$HOST/mutt/credentials $HOME/.mutt/credentials
  fi

fi
