# https://github.com/Homebrew/homebrew-bundle
tap 'caskroom/homebrew-cask'
tap 'homebrew/services'

brew 'browser'
brew 'coreutils'
brew 'dos2unix'
brew 'findutils'
brew 'git'
brew 'git-crypt'
brew 'gnupg'
brew 'grc'
brew 'homebrew/nginx/nginx-full', args: ['with-lua-module', 'with-set-misc-module']
brew 'homebrew/php/php71', restart_service: :changed
brew 'homebrew/php/phpmyadmin'
brew 'jpegoptim'
brew 'jq'
brew 'lynx'
brew 'mercurial'
brew 'mobile-shell'
brew 'mutt'
brew 'mysql', restart_service: :changed
brew 'pngcrush'
brew 'rbenv'
brew 'ripgrep'
brew 'thoughtbot/formulae/rcm'
brew 'tmux'
brew 'vim'
brew 'zsh-completions'
brew 'zsh-lovers'

cask 'alfred'
cask 'caffeine'
cask 'colloquy'
cask 'dash'
cask 'iterm2'
cask 'password-assistant'
cask 'rowanj-gitx'
