#!/bin/sh
# This sets up homedir for you...
# Example usages:
#  wget -q -O- http://willnorris.com/svn/homedir/setup | sh
#  lynx -source http://willnorris.com/svn/homedir/setup | sh
#  curl -o- http://willnorris.com/svn/homedir/setup | sh

# If there is an error, ABORT!
set -e

if [ -e "${HOME}/.homedir/config" ]; then
    echo "You have a homedir configuration already."
    echo "Aborting."
    exit 1
fi

echo "Making ${HOME}/.homedir directory..."
mkdir -p "${HOME}/.homedir/files"

echo "Getting packages..."
svn co -q http://willnorris.com/svn/homedir "${HOME}/.homedir/files"

echo "Basic Configuration..."
touch "${HOME}/.homedir/config"
chmod 0600 "${HOME}/.homedir/config"
cat >> "${HOME}/.homedir/config" <<EOF
## This is a simple config.  It should be good for most cases.
## Read documentation and submit bugs at:
##    http://trac.gerf.org/homedir

## base packages
packages = ~/.homedir/files/packages

## meta packages
packages = ~/.homedir/files/meta-packages

## Command for the -s switch
synccmd = cd ~/.homedir/files ; svn up

## EOF
EOF

echo "Installing Homedir..."
"${HOME}/.homedir/files/packages/00homedir/local/bin/homedir" -q install homedir

echo "Done!"
