#!/bin/sh

if [ -h "$HOME/.ssh/id_dsa" ] && [ `readlink $HOME/.ssh/id_dsa` == "$HOME/.secure/ssh/private.key" ]; then
  rm $HOME/.ssh/id_dsa
fi

if [ -h "$HOME/.ssh/id_dsa.pub" ] && [ `readlink $HOME/.ssh/id_dsa.pub` == "$HOME/.secure/ssh/public.key" ]; then
  rm $HOME/.ssh/id_dsa.pub
fi

