#!/bin/sh

if [ -f "$HOME/.secure/etc/ssh/private.key" ]; then
  if [ ! -h "$HOME/.ssh/id_dsa" ] || [ `readlink $HOME/.ssh/id_dsa` != "$HOME/.secure/etc/ssh/private.key" ]; then
    ln -s $HOME/.secure/etc/ssh/private.key $HOME/.ssh/id_dsa
  fi

fi

if [ -f "$HOME/.secure/etc/ssh/public.key" ]; then
  if [ ! -h "$HOME/.ssh/id_dsa.pub" ] || [ `readlink $HOME/.ssh/id_dsa.pub` != "$HOME/.secure/etc/ssh/public.key" ]; then
    ln -s $HOME/.secure/etc/ssh/public.key $HOME/.ssh/id_dsa.pub
  fi
fi

