#!/bin/sh

HOST=`hostname | cut -d. -f1`

if [ -h "$HOME/.ssh/id_rsa" ] && [ `readlink $HOME/.ssh/id_rsa` == "$HOME/.secure/$HOST/ssh/private.key" ]; then
  rm $HOME/.ssh/id_rsa
fi

if [ -h "$HOME/.ssh/id_rsa.pub" ] && [ `readlink $HOME/.ssh/id_rsa.pub` == "$HOME/.secure/$HOST/ssh/public.key" ]; then
  rm $HOME/.ssh/id_rsa.pub
fi

