#!/bin/sh

apt-get update
apt-get -y install ripgrep tmux zsh

chsh -s /usr/bin/zsh wnorris
rm /home/**/README-cloudshell.txt

ln -s /usr/local/go/bin/* /usr/local/bin/

# install bat
curl -o /tmp/bat.deb -L https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
dpkg -i /tmp/bat.deb
