#!/bin/sh

HOST=`hostname | cut -d. -f1`

if [ -f "$HOME/.secure/$HOST/netrc" ]; then
  if [ ! -h "$HOME/.netrc" ] || [ `readlink $HOME/.netrc` != "$HOME/.secure/$HOST/netrc" ]; then
    ln -s $HOME/.secure/$HOST/netrc $HOME/.netrc
  fi
fi

