#!/bin/sh

HOST=`hostname | cut -d. -f1`

if [ -f "$HOME/.secure/$HOST/gpg/secring.gpg" ]; then
  if [ ! -h "$HOME/.gnupg/secring.gpg" ] || [ `readlink $HOME/.gnupg/secring.gpg` != "$HOME/.secure/$HOST/gpg/secring.gpg" ]; then
    ln -s $HOME/.secure/$HOST/gpg/secring.gpg $HOME/.gnupg/secring.gpg
  fi
fi

if [ -f "$HOME/.secure/$HOST/gpg/pubring.gpg" ]; then
  if [ ! -h "$HOME/.gnupg/pubring.gpg" ] || [ `readlink $HOME/.gnupg/pubring.gpg` != "$HOME/.secure/$HOST/gpg/pubring.gpg" ]; then
    ln -s $HOME/.secure/$HOST/gpg/pubring.gpg $HOME/.gnupg/pubring.gpg
  fi
fi

