#!/bin/sh

HOST=`hostname | cut -d. -f1`

if [ -h "$HOME/.gnupg/secring.gpg" ] && [ `readlink $HOME/.gnupg/secring.gpg` == "$HOME/.secure/$HOST/gpg/secring.gpg" ]; then
  rm $HOME/.gnupg/secring.gpg
fi

if [ -h "$HOME/.gnupg/pubring.gpg" ] && [ `readlink $HOME/.gnupg/pubring.gpg` == "$HOME/.secure/$HOST/gpg/pubring.gpg" ]; then
  rm $HOME/.gnupg/pubring.gpg
fi

