#!/bin/sh

if [ -f "$HOME/.secure/etc/gpg/secring.gpg" ]; then
  if [ ! -h "$HOME/.gnupg/secring.gpg" ] || [ `readlink $HOME/.gnupg/secring.gpg` != "$HOME/.secure/etc/gpg/secring.gpg" ]; then
    ln -s $HOME/.secure/etc/gpg/secring.gpg $HOME/.gnupg/secring.gpg
  fi
fi

if [ -f "$HOME/.secure/etc/gpg/pubring.gpg" ]; then
  if [ ! -h "$HOME/.gnupg/pubring.gpg" ] || [ `readlink $HOME/.gnupg/pubring.gpg` != "$HOME/.secure/etc/gpg/pubring.gpg" ]; then
    ln -s $HOME/.secure/etc/gpg/pubring.gpg $HOME/.gnupg/pubring.gpg
  fi
fi

