#!/bin/sh

# Add the specified folder to the specified PATH-like environment variable, if
# it is not already present.
#
# Example usage: addToPathVar PATH /usr/local/bin

eval local v=\$$1
if [ -z "$v" ]; then
  [ -d $2 ] && eval $1=$2
else
  [ -d $2 ] && [ ! `echo $v | egrep "(^|:)$2(:|$)"` ] && eval $1=$2:\$$1
fi
