#!/bin/sh

# ts provides a simple wrapper around tmux named sessions.

if [ $# -eq 1 ]; then
  tmux attach -t $1 2>/dev/null || tmux new-session -s $1
else
  echo "ts - create or attach to the specified tmux session"
  echo "Usage: ts <session-name>\n"

  sessions=`tmux list-sessions 2>/dev/null`
  if [ -n "$sessions" ]; then
    echo "Active sessions:"
    echo $sessions | awk '{ print "  "$0 }'
  else
    echo "No active sessions."
  fi
fi
