# vim: ft=zsh

typeset -U path manpath
autoload -U compinit && compinit

# load common shell configuration
if [ -f "${HOME}/.profile" ]; then
  source "${HOME}/.profile"
fi

for config_file (${XDG_CONFIG_HOME}/zsh/startup/*.zsh(rN)); do
  source $config_file
done

manpath=($XDG_DATA_HOME/man $manpath)
export MANPATH="$MANPATH:"
