#!/bin/sh

HOST=`hostname | cut -d. -f1`

function install_file() {
  if [ -f "$HOME/.secure/$HOST/$1" ]; then
    if [ ! -h "$HOME/$2" ] || [ `readlink $HOME/$2` != "$HOME/.secure/$HOST/$1" ]; then
      ln -s $HOME/.secure/$HOST/$1 $HOME/$2
    fi
  fi
}

install_file "gpg/secring.gpg"  ".gnupg/secring.gpg"
install_file "gpg/pubring.gpg"  ".gnupg/pubring.gpg"
