#!/bin/bash

mkdir -p $HOME/.vim/undo
chmod 700 $HOME/.vim/undo

mkdir -p $HOME/.vim/bundle
if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
  curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim +PlugInstall +qall
