#!/bin/bash

mkdir -p "${XDG_CONFIG_HOME}/zsh/bundle"
if [ ! -d "${XDG_CONFIG_HOME}/zsh/bundle/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "${XDG_CONFIG_HOME}/zsh/bundle/zsh-syntax-highlighting"
fi
