#!/usr/bin/zsh

. "${HOME}/.config/shell/_xdg_base.sh"

ln -s zprofile "${XDG_CONFIG_HOME}/zsh/.zprofile"
ln -s zshrc "${XDG_CONFIG_HOME}/zsh/.zshrc"
ln -s "${XDG_CONFIG_HOME}/zsh/zshenv" "${HOME}/.zshenv"

mkdir -p "${XDG_CONFIG_HOME}/zsh/bundle"
if [ ! -d "${XDG_CONFIG_HOME}/zsh/bundle/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "${XDG_CONFIG_HOME}/zsh/bundle/zsh-syntax-highlighting"
fi

mkdir -p "${XDG_DATA_HOME}/zsh"
